# Generated by Django 2.0.6 on 2018-06-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerfile',
            name='answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pyp.Answer'),
        ),
    ]
