# Generated by Django 2.0.6 on 2018-07-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0004_auto_20180727_1347'),
        ('pyp', '0004_auto_20180727_1356'),
    ]

    operations = [
    ]
